FROM ghcr.io/m1k1o/neko/firefox:latest

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      nano && \
    rm -rf /var/lib/apt/lists/*

ENV NEKO_MEMBER_PROVIDER=multiuser
ENV NEKO_MEMBER_MULTIUSER_USER_PASSWORD=neko
ENV NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD=admin
ENV NEKO_WEBRTC_ICELITE=true
ENV NEKO_WEBRTC_EPR=52000-52000
ENV NEKO_WEBRTC_NAT1TO1=127.0.0.1

EXPOSE 8080
EXPOSE 52000/udp
