FROM golang:1.25 AS build
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/provisioner ./cmd/provisioner

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=build /out/provisioner /provisioner
ENTRYPOINT ["/provisioner"]
