FROM ghcr.io/selkies-project/selkies-gstreamer/gst-py-example:main-ubuntu24.04

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      nano && \
    rm -rf /var/lib/apt/lists/*

ENV SELKIES_BASIC_AUTH_USER=ubuntu
ENV SELKIES_BASIC_AUTH_PASSWORD=mypasswd
ENV SELKIES_ENABLE_HTTPS=false

EXPOSE 8080
