ARG BASE_USER_IMAGE=crypticstack/probable-adventure-base-user:bookworm-xfce
FROM ${BASE_USER_IMAGE}

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      iproute2 \
      iputils-ping \
      dnsutils \
      net-tools && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080
EXPOSE 52000/udp
