FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      git \
      nano \
      tini \
      shellinabox \
      iproute2 \
      iputils-ping \
      dnsutils \
      netcat-openbsd \
      nmap \
      tcpdump \
      traceroute && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 7681

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["shellinaboxd", "-t", "--disable-ssl", "-s", "/:LOGIN", "-p", "7681"]
