ARG BASE_SERVER_IMAGE=crypticstack/probable-adventure-base-server:bookworm
FROM ${BASE_SERVER_IMAGE}

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      iproute2 \
      iputils-ping \
      dnsutils \
      netcat-openbsd \
      nmap \
      tcpdump \
      traceroute && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8080
